server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ESTUserService?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: boyoung
    password: boyoung0903
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
  jwt:
    secret: fleogpvmzzalstkfkdgodyroqkfwkdbalroqkfwkdbalajekfitospldvnewfekdl

#springdoc:
#  show-login-endpoint: true
