name: cicd for user-service
on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  IMAGE_NAME: esthete-user-service

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Determine and Push Next Version Tag
        run: |
          if ! git tag --sort version:refname | grep -q .; then
            git tag 1.0.0
          else
            NEXT_USER_VER=$(git tag --sort version:refname | tail -n 1 | awk -F. -v OFS=. '{$NF++; print}')
            git tag $NEXT_USER_VER
          fi
          git push --tags
          echo "NEXT_USER_VER=$NEXT_USER_VER" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.NEXT_USER_VER }}
          platforms: linux/arm64

      - name: Deploy to test server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST_DNS }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA,NEXT_USER_VER
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.NEXT_USER_VER }}
            sudo docker stop ${{ env.IMAGE_NAME }} || true
            sudo docker rm ${{ env.IMAGE_NAME }} || true
            sudo docker run -d --name ${{ env.IMAGE_NAME }} --network esthete-network -p 8020:8020 \
                -v /var/log/user-service:/app/logs \
                -e ACCESS_EXPIRATION='${{ secrets.ACCESS_EXPIRATION }}' \
                -e DB_HOST='${{ secrets.DB_HOST }}' \
                -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
                -e DB_PORT='${{ secrets.DB_PORT }}' \
                -e DB_USERNAME='${{ secrets.DB_USERNAME }}' \
                -e INITIAL_DB='${{ secrets.INITIAL_DB }}' \
                -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
                -e SPRING_DATASOURCE_DDL_AUTO='${{ secrets.SPRING_DATASOURCE_DDL_AUTO }}' \
                -e REDIS_HOST='${{ secrets.REDIS_HOST }}' \
                -e REDIS_PORT='${{ secrets.REDIS_PORT }}' \
                -e MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}' \
                -e MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}' \
                -e REFRESH_EXPIRATION='${{ secrets.REFRESH_EXPIRATION }}' \
                ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.NEXT_USER_VER }} || true
            sleep 15
            sudo docker image prune -af || true
            sudo docker images ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }} | grep -v ${{ env.NEXT_USER_VER }} | awk '{print $3}' | xargs -r sudo docker rmi || true
